name: expense
networks:
  default:
    name: expense
services:
  mysql:
    image: mysql:v1.0.0
    container_name: mysql # --name mysql
  backend:
    image: backend:v1.0.0
    container_name: backend
    depends_on: 
    - mysql
  frontend:
    image: frontend:v1.0.0
    container_name: frontend
    depends_on:
    - backend
    ports:
    - "80:80"